### ISSUE TITLE
prepare 2018.06-beta1 ISO

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/2018.08#1]
idea is to release at end of june/early july

**Comment by star-buck** [comment]
@NuLogicSystems : please let me know the status, like you started setting up the iso, etc.

**Comment by NuLogicSystems** [comment]
I'm out of town on vacation with my son until Monday evening.
I'll do what I can via the web interface at night until I get back.
Once I'm back, I can start on the more involved parts of building the ISO's.

**Comment by star-buck** [comment]
Great, thanks for the update.

**Comment by NuLogicSystems** [comment]
Uploading ISO now, should be completely up in about an hour.
I'm having some rsync errors (broken pipe 32) ATM, I'm not sure what that's about.

**Comment by NuLogicSystems** [comment]
OK, that took longer than expected.
I'm still not sure what's causing the issue, I had to restart it a bunch of times.
Well, at least it finally finished:
http://arch.netrunner.com/ISO/netrunner-rolling-2018.06-beta1-x86_64.iso
http://arch.netrunner.com/ISO/netrunner-rolling-2018.06-beta1-x86_64.iso.sha256sum

**Comment by star-buck** [comment]
Hi James,

do you know when Manjaro will feature Plasma 5.13?
That would be nice to update for next beta2 iso.

Greetings, Clemens.

**Comment by NuLogicSystems** [comment]
Should. already on beta one ISO, I built it from testing branch.
However, I've found quite a few issues with it that I'm trying to fix.
System Settings is messed all up again.
I also found a couple of other minor issues that came along with the update that I need to fix.

**Comment by star-buck** [comment]
Whats the reason for this?
Would SS also be messed up when updating NRR 2018.01 to Plasma 5.13?

**Comment by NuLogicSystems** [comment]
I don't know exactly, that's what I'm trying to figure out.
Yes it would, here is what I have on my NRR system running on testing brach:
![screenshot_20180619_005134](https://user-images.githubusercontent.com/10186587/41577520-41ee0206-735b-11e8-96ca-f7ed16b39ff4.png)
![screenshot_20180619_005222](https://user-images.githubusercontent.com/10186587/41577521-4201c7aa-735b-11e8-859e-78f368f981cb.png)

Kind of looks like a hybrid of our diversion and system defaults.
I'll need to compare our desktop files to theirs, but it's almost 1:00am and I need to get some sleep.
They seem to have also added some new things, that plasma renderer kcm is new.

**Comment by NuLogicSystems** [comment]
Yea, they changed alot of stuff.
kcm_input is now kcm_mouse so the mouse settings in our diversion will not load anymore.
I may need to edit a quite a few files in our diversion.

**Comment by star-buck** [comment]
Can you see to make it universal?
So also netrunner debian benefits from the general corrections.

**Comment by NuLogicSystems** [comment]
I'll look through them some more in the morning and try to get this back to normal.
I might need to ask for some feedback at some point on where to put some of the new kcm's I run accross, like plasma renderer, etc. Yes, once I do get these all fixed up i'll make sure to pass along the common universal changes to netrunner debian. The MSM ksm's do not seem to be effected, just the upstream plasma-desktop kcm's.

**Comment by star-buck** [comment]
I can sort this pretty quickly, so dont worry about this.
Only thing is how to share the non-manjaro kcm fixes with netrunner debian.

**Comment by NuLogicSystems** [comment]
The MSM kcm's are all labeled as such, shouldn't be much of a problem.
It's just that it's not just a sorting issue, they actually changed the backends to some things.
For example, kcm_input no longer exist at all, it was replaced with kcm_mouse, which looks completely new.
They also added something called a X-KDE-Init-Phase=xx to some of the desktop files.

**Comment by star-buck** [comment]
Okay, so if you get stuff fixed, then just see if you can opy them over to
the netrunner debian repos.

On Jun 18, 2018 22:46, "James Kittsmiller" <notifications@github.com> wrote:

The MSM kcm's are all labeled as such, shouldn't be much of a problem.
It's just that it's not just a sorting issue, they actually changed the
backends to some things.
For example, kcm_input no longer exist, kcm_mouse is completely new.
They also added something called a X-KDE-Init-Phase=0 to some of the
desktop files.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/netrunner-rolling/2018.06/issues/1#issuecomment-398281381>,
or mute the thread

**Comment by NuLogicSystems** [comment]
Will do. Will probably need to be done in a branch though at least until the debian editions get plasma 5.13.

**Comment by NuLogicSystems** [comment]
Well, workspaceoptions no longer exists in 5.13 either.
This is going to be fun.

**Comment by NuLogicSystems** [comment]
OK, done.
Now on to testing them.

**Comment by NuLogicSystems** [comment]
I just found this, Manjaro is keeping bug reports on plasma 5.13 and frameworks 5.47 here:
https://forum.manjaro.org/t/plasma-5-13-0-and-kde-framework-5-47-bugs/50034

**Comment by NuLogicSystems** [comment]
Building a beta 1b now. I will rsync it when it's finished for you to check.

**Comment by NuLogicSystems** [comment]
I wish I know what is going on with sshpass, rsync, and/or ssh.
Anyway, beta1b is now on the server.

**Comment by NuLogicSystems** [comment]
Before I commit the system settings changes to the debian editions (ds9-common), could you please check the ISO to verify I still have everything in the right places?

**Comment by NuLogicSystems** [comment]
OK, I made commits for debian editions:
https://github.com/ds9-common/default-systemsettings-settings

Should be good to go once Plasma 5.13.x hits Debian editions.
Albiet, some more clean up of old unused, and/or unmodified from upstream, diversions should be performed.

**Comment by NuLogicSystems** [comment]
Beta2 ISO now uploaded:

kernel 4.17
plasma-desktop 5.13.1.1
plasma-framework 5.47.0-1.1
kde applications 18.04.2
qt5 5.11.1

http://arch.netrunner.com/ISO/netrunner-rolling-2018.06-beta2-x86_64.iso
http://arch.netrunner.com/ISO/netrunner-rolling-2018.06-beta2-x86_64.iso.sha256sum

**Comment by star-buck** [comment]
Hi James,

at some point in the near future, we need to switch to standard release
channel.
I suggest to look out whenever 5.13 Plasma hits the official channel.

**Comment by NuLogicSystems** [comment]
Yes, I agree.. 
Plasma 5.13.x has been very buggy so Manjaro held back until upstream KDE fixed all these major bugs, and arch packaged them. Manjaro is in the final test stretch for plasma 5.13.1.1 before pushing it to stable, at that point I plan and moving some of our packages and building the next ISO based on stable.

I could still use a new wallpaper though.
