### ISSUE TITLE
add wallpaper, make "Rolling 2018.06" default

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/2018.08#11]
then just spin another rc3 ISO, I will do some more tests next week.

**Comment by star-buck** [comment]
@NuLogicSystems : Please wait, it looks like those two are going to be updated once more by the designer...

**Comment by NuLogicSystems** [comment]
OK, just let me know when they are ready. ;)

**Comment by star-buck** [comment]
This is the final wallpaper, just add this one and make default:
https://www.dropbox.com/s/oo7kd2dw6mkins4/Rolling%202018.06.jpg?dl=0

**Comment by NuLogicSystems** [comment]
Will do, first thing in the morning.

**Comment by NuLogicSystems** [comment]
Done
