### ISSUE TITLE
Firefox window comes up after start, but is at the same time not found under systray?

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/2018.08#2]
It should be the other way around: Found autostarted under systray but NOT coming up.

**Comment by star-buck** [comment]
this seems only true for the first time rolling is started right after it got installed.

**Comment by NuLogicSystems** [comment]
I think that might be due to one of the extensions, one of them has a tendency to open a new tab when installed/updated.

**Comment by NuLogicSystems** [comment]
Could also be due to Firefox still running in the background (KSysTrayCmd) when the system is shutdown.
I've noticed Firefox will sometimes act as if it crashed and give you the restore window when this happens.

**Comment by star-buck** [comment]
Thats a good explanation!
Now what to do in that case?

**Comment by NuLogicSystems** [comment]
I think this fixed it.
browser.sessionstore.resume_from_crash;false
