### ISSUE TITLE
Octopi: remove netrunner-testing repo in next RC ISO

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/2018.08#7]
![screenshot_20180629_105637](https://user-images.githubusercontent.com/840070/42089650-beedf70e-7b8d-11e8-9bd3-ec0348e8dfcd.png)

**Comment by star-buck** [comment]
it seems enabled default, so at least disable it

**Comment by NuLogicSystems** [comment]
Until Plasma 5.13.x is in Manjaro stable there are packages in that repo needed for the ISO that I can not yet move. I will need to wait for upstream to move plasma 5.13.x into stable before I can disable that repository. (mainly our updated system settings diversion will break in plasma 5.12)

**Comment by NuLogicSystems** [comment]
Done, building ISO now.

**Comment by star-buck** [comment]
awesome.
please let me know when ISO is done.

**Comment by NuLogicSystems** [comment]
Done, rc1 Iso is now uploaded to the server.

**Comment by NuLogicSystems** [comment]
I uploaded an rc2 ISO to the server.
Kernel 4.17.3
Plasma 5.13.2
Frameworks 5.47.0
KDE applications 18.04.2
Qt5 5.11.1
