### ISSUE TITLE
Please re-add package BlackX Desktop Theme

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/2018.08#8]
not sure why it was removed, just wanted the default theme to switch:
https://github.com/ds9-artwork/desktop-theme-blackx

Please re-package as it was likely old anyway and the new got updated to suit the download functionality.

**Comment by NuLogicSystems** [comment]
No Problem, I didn't realize I had removed it.

**Comment by NuLogicSystems** [comment]
Done
