### ISSUE TITLE
Manjaro no longer providing Plasma-based Firefox? File-dialog is GTK...

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/2018.08#9]

**Comment by NuLogicSystems** [comment]
No they don't, Manjaro droped the firefox-kde and thunderbird-kde packages way back in December 2017. They decided it wasn't worth the compilation times or resources of their build system for little to no benefit.

https://forum.manjaro.org/t/stable-update-2017-12-03-kernels-mesa-firefox-thunderbird-plasma5/35810?source_topic_id=36827

**Comment by NuLogicSystems** [comment]
However, there is this:
https://forum.manjaro.org/t/firefox-firefox-kde-repository/35969

**Comment by hphilm** [comment]
We additionally had a 3rd-party repo for [firefox-kde](https://forum.manjaro.org/t/firefox-firefox-kde-repository-eol-no-support-anymore/35969/246), which however is now EOL as well.

Long story short: He decided to give up on **firefox-kde**.

Two reasons for this:

- He wants to spend his real life time a little differently
- **firefox-kde-opensuse** is in AUR and also has a repo with prebuilt binaries (although for Arch); it’s also more complete than his version, and why the double work?

```
[home-thaodan]
Server = <https://thaodan.de/home/bidar/home-thaodan/x86_64/>
```
The key needs to be imported or distributed:

```
sudo pacman-key --recv-keys BBFE2FD421597395E4FC8C8DF6C85FEE79D661A4
pacman-key --finger BBFE2FD421597395E4FC8C8DF6C85FEE79D661A4
sudo pacman-key --lsign-key  BBFE2FD421597395E4FC8C8DF6C85FEE79D661A4
sudo pacman-key --refresh-keys
```
A possibility would be, to redistribute that package on our repos.

**Comment by star-buck** [comment]
> A possibility would be, to redistribute that package on our repos.

That would be nice, if it doesnt lead to a conflict with the normal firefox package.

**Comment by NuLogicSystems** [comment]
Yes, redistributing that package in the Manjaro repositories would be nice.

**Comment by NuLogicSystems** [comment]
@star-buck 
The firefox-kde-opensuse package is now in the Manjaro stable branch.

**Comment by star-buck** [comment]
Yes, lets try it.

**Comment by NuLogicSystems** [comment]
I'll build an RC6 ISO with it then. ;)

**Comment by NuLogicSystems** [comment]
Done: http://arch.netrunner.com/ISO/netrunner-rolling-2018.06-rc6-x86_64.iso
